### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by whyleee** [alfnilsson/EPiEventHelper#1]
We're using this library for a while and it will be great to get it from NuGet instead of manual compilation and copy-pasting dll's.

**Comment by dnasir** [comment]
+1

I hope you can release this to NuGet.

**Comment by whyleee** [comment]
I published the package to nuget.org: https://www.nuget.org/packages/EPiEventHelper/

**Comment by alfnilsson** [comment]
Thanks for the feedback and thanks Whyleee!
